SNAPSHOT_PAYLOAD = {'generatedAt': '2026-05-06T19:20:01.631222+00:00',
 'signalDate': '2026-05-05',
 'sourceFiles': {'predictionCsv': 'sample_predictions_with_tiers_20260505.csv',
                 'selectorCsv': 'top_trades_latest.csv',
                 'strategyStats': 'trades_master.duckdb',
                 'sectorOutlookWorkbook': 'ml_predictions_summary_lgbm_bigwin25_calls_v1_20260505.xlsx',
                 'marketRegime': 'macro_regime_enriched.csv',
                 'tradesDb': 'trades_master.duckdb'},
 'recordCounts': {'candidateTrades': 6, 'returnedTrades': 6, 'yesterdayStatus': 0, 'sectorCount': 6},
 'marketRegime': {'date': '2026-05-05',
                  'regime': 'Neutral-to-Supportive',
                  'summary': 'VIX is moderate at 17.4, SPY trend is mildly supportive, and shock-day risk is off.',
                  'vix': {'level': 17.38, 'label': 'Moderate', 'momentum3d': 0.16, 'percentile': 55.9},
                  'spy': {'return1d': 0.8, 'trend3d': 0.2, 'trend5d': 0.3, 'trendLabel': 'Mildly Supportive'},
                  'risk': {'shockDay': False, 'trendStrength': 0.42},
                  'insight': 'System Insight: Multiple entry-grade setups available; prioritize clean entries over '
                             'extended momentum.'},
 'strategyStats': {'highConviction': {'winRate': 61.8,
                                      'sampleSize': 849,
                                      'tickerCount': 39,
                                      'minDate': '2026-04-06',
                                      'maxDate': '2026-04-27',
                                      'avgReturnPct': 93.3,
                                      'medianReturnPct': 52.0,
                                      'lossRate': 37.7,
                                      'largeLossRate': 22.7,
                                      'worstDrawdownProxy': None,
                                      'returnDistribution': [{'range': '<-50%', 'count': 117, 'percentage': 13.8},
                                                             {'range': '-50%â\x80\x930%',
                                                              'count': 203,
                                                              'percentage': 23.9},
                                                             {'range': '0â\x80\x9350%',
                                                              'count': 99,
                                                              'percentage': 11.7},
                                                             {'range': '50â\x80\x93150%',
                                                              'count': 167,
                                                              'percentage': 19.7},
                                                             {'range': '>150%', 'count': 263, 'percentage': 31.0}],
                                      'equityCurve': [{'date': '2026-04-06', 'value': 989.3},
                                                      {'date': '2026-04-07', 'value': 1036.2},
                                                      {'date': '2026-04-08', 'value': 1569.1},
                                                      {'date': '2026-04-09', 'value': 8605.0},
                                                      {'date': '2026-04-10', 'value': 15126.5},
                                                      {'date': '2026-04-13', 'value': 22724.9},
                                                      {'date': '2026-04-14', 'value': 33368.1},
                                                      {'date': '2026-04-15', 'value': 42970.3},
                                                      {'date': '2026-04-16', 'value': 57091.9},
                                                      {'date': '2026-04-17', 'value': 67138.8},
                                                      {'date': '2026-04-20', 'value': 68876.6},
                                                      {'date': '2026-04-21', 'value': 71046.7},
                                                      {'date': '2026-04-22', 'value': 73548.1},
                                                      {'date': '2026-04-23', 'value': 76410.5},
                                                      {'date': '2026-04-24', 'value': 76163.1},
                                                      {'date': '2026-04-27', 'value': 79248.7}],
                                      'label': 'Cohort A'},
                   'broadBase': {'winRate': 64.6,
                                 'sampleSize': 1457,
                                 'tickerCount': 67,
                                 'minDate': '2026-04-06',
                                 'maxDate': '2026-04-27',
                                 'avgReturnPct': 91.3,
                                 'medianReturnPct': 40.7,
                                 'lossRate': 34.9,
                                 'largeLossRate': 18.1,
                                 'worstDrawdownProxy': None,
                                 'returnDistribution': [{'range': '<-50%', 'count': 147, 'percentage': 10.1},
                                                        {'range': '-50%â\x80\x930%', 'count': 361, 'percentage': 24.8},
                                                        {'range': '0â\x80\x9350%', 'count': 251, 'percentage': 17.2},
                                                        {'range': '50â\x80\x93150%', 'count': 239, 'percentage': 16.4},
                                                        {'range': '>150%', 'count': 459, 'percentage': 31.5}],
                                 'equityCurve': [{'date': '2026-04-06', 'value': 10760.3},
                                                 {'date': '2026-04-07', 'value': 22531.9},
                                                 {'date': '2026-04-08', 'value': 35522.7},
                                                 {'date': '2026-04-09', 'value': 44696.5},
                                                 {'date': '2026-04-10', 'value': 48818.6},
                                                 {'date': '2026-04-13', 'value': 55714.8},
                                                 {'date': '2026-04-14', 'value': 68717.9},
                                                 {'date': '2026-04-15', 'value': 81360.0},
                                                 {'date': '2026-04-16', 'value': 97224.5},
                                                 {'date': '2026-04-17', 'value': 105726.0},
                                                 {'date': '2026-04-20', 'value': 110313.6},
                                                 {'date': '2026-04-21', 'value': 115542.1},
                                                 {'date': '2026-04-22', 'value': 121007.1},
                                                 {'date': '2026-04-23', 'value': 127089.3},
                                                 {'date': '2026-04-24', 'value': 128136.7},
                                                 {'date': '2026-04-27', 'value': 133025.7}],
                                 'label': 'Cohort B'}},
 'sectorOutlook': [{'rank': 1,
                    'sector': 'Technology',
                    'etf': 'XLK',
                    'bias': 'No overlay',
                    'totalSignals': 11505,
                    'strongSignalCount': 269,
                    'aTierDensity': 2.3,
                    'netScore': 1412.98,
                    'convictionScore': 0.1228,
                    'flowSkew': 'Call-led',
                    'topTickers': [{'ticker': 'ORCL',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 35,
                                    'signalCount': 144},
                                   {'ticker': 'QCOM',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 19,
                                    'signalCount': 100},
                                   {'ticker': 'MSTR',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 19,
                                    'signalCount': 132}],
                    'tickerCount': 468,
                    'aTierTickerCount': 42,
                    'top1Share': 13.0,
                    'top3Share': 27.1,
                    'avgBestScore': 0.2066,
                    'top5AvgScore': 1.4431,
                    'sectorScore': 1.9835,
                    'rawBreadth': 6.1506,
                    'cappedBreadth': 6.0,
                    'previousRank': 1},
                   {'rank': 2,
                    'sector': 'Industrials',
                    'etf': 'XLI',
                    'bias': 'No overlay',
                    'totalSignals': 4713,
                    'strongSignalCount': 22,
                    'aTierDensity': 0.5,
                    'netScore': 143.04,
                    'convictionScore': 0.0304,
                    'flowSkew': 'Call-led',
                    'topTickers': [{'ticker': 'BA',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 8,
                                    'signalCount': 79},
                                   {'ticker': 'GE',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 6,
                                    'signalCount': 40},
                                   {'ticker': 'BE',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 2,
                                    'signalCount': 68}],
                    'tickerCount': 364,
                    'aTierTickerCount': 8,
                    'top1Share': 36.4,
                    'top3Share': 72.7,
                    'avgBestScore': 0.0661,
                    'top5AvgScore': 1.0548,
                    'sectorScore': 1.7272,
                    'rawBreadth': 5.8999,
                    'cappedBreadth': 5.8999,
                    'previousRank': 5},
                   {'rank': 3,
                    'sector': 'Financial Services',
                    'etf': 'XLF',
                    'bias': 'No overlay',
                    'totalSignals': 3587,
                    'strongSignalCount': 23,
                    'aTierDensity': 0.6,
                    'netScore': 29.73,
                    'convictionScore': 0.0083,
                    'flowSkew': 'Balanced',
                    'topTickers': [{'ticker': 'COIN',
                                    'grade': 'Sell',
                                    'direction': 'Neutral',
                                    'aGradeCount': 11,
                                    'signalCount': 121},
                                   {'ticker': 'JPM',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 5,
                                    'signalCount': 39},
                                   {'ticker': 'BX',
                                    'grade': 'Sell',
                                    'direction': 'Neutral',
                                    'aGradeCount': 3,
                                    'signalCount': 51}],
                    'tickerCount': 338,
                    'aTierTickerCount': 5,
                    'top1Share': 47.8,
                    'top3Share': 82.6,
                    'avgBestScore': -0.094,
                    'top5AvgScore': 0.9626,
                    'sectorScore': 1.6183,
                    'rawBreadth': 5.826,
                    'cappedBreadth': 5.826,
                    'previousRank': 8},
                   {'rank': 4,
                    'sector': 'Healthcare',
                    'etf': 'XLV',
                    'bias': 'No overlay',
                    'totalSignals': 5468,
                    'strongSignalCount': 8,
                    'aTierDensity': 0.1,
                    'netScore': 13.0,
                    'convictionScore': 0.0024,
                    'flowSkew': 'Balanced',
                    'topTickers': [{'ticker': 'ABVX',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 3,
                                    'signalCount': 35},
                                   {'ticker': 'NTRA',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 1,
                                    'signalCount': 3},
                                   {'ticker': 'JNJ',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 1,
                                    'signalCount': 21}],
                    'tickerCount': 588,
                    'aTierTickerCount': 6,
                    'top1Share': 37.5,
                    'top3Share': 62.5,
                    'avgBestScore': -0.1996,
                    'top5AvgScore': 0.8736,
                    'sectorScore': 1.5769,
                    'rawBreadth': 6.3784,
                    'cappedBreadth': 6.0,
                    'previousRank': 10},
                   {'rank': 5,
                    'sector': 'Consumer Cyclical',
                    'etf': 'XLY',
                    'bias': 'Bullish',
                    'totalSignals': 4591,
                    'strongSignalCount': 22,
                    'aTierDensity': 0.5,
                    'netScore': 43.12,
                    'convictionScore': 0.0094,
                    'flowSkew': 'Balanced',
                    'topTickers': [{'ticker': 'AMZN',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 18,
                                    'signalCount': 101},
                                   {'ticker': 'ABNB',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 1,
                                    'signalCount': 43},
                                   {'ticker': 'BABA',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 1,
                                    'signalCount': 41}],
                    'tickerCount': 328,
                    'aTierTickerCount': 5,
                    'top1Share': 81.8,
                    'top3Share': 90.9,
                    'avgBestScore': -0.0731,
                    'top5AvgScore': 0.8656,
                    'sectorScore': 1.5701,
                    'rawBreadth': 5.7961,
                    'cappedBreadth': 5.7961,
                    'previousRank': 7},
                   {'rank': 6,
                    'sector': 'Energy',
                    'etf': 'XLE',
                    'bias': 'No overlay',
                    'totalSignals': 2519,
                    'strongSignalCount': 23,
                    'aTierDensity': 0.9,
                    'netScore': 145.4,
                    'convictionScore': 0.0577,
                    'flowSkew': 'Call-led',
                    'topTickers': [{'ticker': 'MPC',
                                    'grade': 'Strong Buy',
                                    'direction': 'Neutral',
                                    'aGradeCount': 5,
                                    'signalCount': 16},
                                   {'ticker': 'CVX',
                                    'grade': 'Hold',
                                    'direction': 'Neutral',
                                    'aGradeCount': 4,
                                    'signalCount': 46},
                                   {'ticker': 'CCJ',
                                    'grade': 'Sell',
                                    'direction': 'Neutral',
                                    'aGradeCount': 4,
                                    'signalCount': 67}],
                    'tickerCount': 165,
                    'aTierTickerCount': 10,
                    'top1Share': 21.7,
                    'top3Share': 56.5,
                    'avgBestScore': 0.041,
                    'top5AvgScore': 1.0647,
                    'sectorScore': 1.5671,
                    'rawBreadth': 5.112,
                    'cappedBreadth': 5.112,
                    'previousRank': 3}],
 'yesterdayStatus': [],
 'trades': [{'rank': 1,
             'selector_rank': 1,
             'ticker': 'NUE',
             'signal_date': '2026-05-05',
             'companyName': 'Nucor Corporation',
             'tier': 'A+',
             'final_tier': 'A+',
             'action': 'WAIT',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 99.719367,
             'global_percentile': 99.879958,
             'adaptive_score_final': 1.711901,
             'contract': {'optionSymbol': 'O:NUE260618C00200000',
                          'strike': 200,
                          'expiry': '2026-06-18',
                          'dte': 44,
                          'underlyingPrice': 232.07,
                          'distanceToStrikePct': -13.8,
                          'moneyness': '0.862',
                          'itmFlag': 'ITM',
                          'strikePositionLabel': 'ITM',
                          'strikePositionText': '13.8% below spot'},
             'market': {'volume': 56, 'openInterest': 848},
             'context': {'sector': 'Basic Materials', 'rsi': 83.0},
             'etfOverlay': {'etf': 'XLB', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.712,
                        'adjustedScoreFinal': 2.123,
                        'adaptiveScore': 1.712,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': None,
                        'recentWr': None,
                        'recentN': 0,
                        'degradation': None,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -9.33,
                        'evPct': -0.23,
                        'rankScore': 0.162,
                        'regimeAdj': 0.0,
                        'sectorScore': -0.242,
                        'rsiScore': 1.224},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'A',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': None,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 41.4,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': ['ITM structure supports follow-through if trend holds.'],
                                   'caution': ['No live sector overlay; use price action to confirm.',
                                               'Momentum extended; avoid chasing strength.'],
                                   'unfavorable': ['Behind stronger names today; only revisit if conditions improve.']},
             'decisionContext': {'today': {'rank': 1, 'candidateCount': 6, 'topPercent': 17, 'todayScore': 100},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': 21,
                                                'distinctTickerCount': 5,
                                                'winRate': 85.7,
                                                'avgReturnPct': 126.8,
                                                'avgRMultiple': None,
                                                'medianHoldDays': 9.0,
                                                'holdP25Days': 8.0,
                                                'holdP75Days': 9.0,
                                                'cohortLabel': 'Based on similar setups over the last 90 days',
                                                'matchStrength': 'setup',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Broadly qualified, but not a priority versus cleaner names today.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   'RSI 83.0 is elevated, so timing needs more care.'],
                                 'invalidation': ['Skip if price moves more than 2% above the snapshot before entry.',
                                                  'Skip if momentum extends further without a reset.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '8-9 trading days',
                                                 'baseCase': 'Secondary setup unless the tape improves.',
                                                 'risk': 'The edge weakens if momentum cools and sector support '
                                                         'fades.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}},
            {'rank': 2,
             'selector_rank': 2,
             'ticker': 'NBIS',
             'signal_date': '2026-05-05',
             'companyName': 'Nebius Group N.V.',
             'tier': 'A+',
             'final_tier': 'A+',
             'action': 'ENTER',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 99.469714,
             'global_percentile': 99.770022,
             'adaptive_score_final': 1.631342,
             'contract': {'optionSymbol': 'O:NBIS260529C00200000',
                          'strike': 200,
                          'expiry': '2026-05-29',
                          'dte': 24,
                          'underlyingPrice': 175.92,
                          'distanceToStrikePct': 13.7,
                          'moneyness': '1.137',
                          'itmFlag': 'OTM',
                          'strikePositionLabel': 'OTM',
                          'strikePositionText': '13.7% above spot'},
             'market': {'volume': 244, 'openInterest': 1127},
             'context': {'sector': 'Communication Services', 'rsi': 50.9},
             'etfOverlay': {'etf': 'XLC', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.631,
                        'adjustedScoreFinal': 1.426,
                        'adaptiveScore': 1.431,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': None,
                        'recentWr': None,
                        'recentN': 0,
                        'degradation': None,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -2.925,
                        'evPct': -0.25,
                        'rankScore': 0.217,
                        'regimeAdj': 0.2,
                        'sectorScore': 2.0,
                        'rsiScore': 0.296},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'A',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': False,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 11.7,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': ["Higher-priority candidate in today's list."],
                                   'caution': ['No live sector overlay; use price action to confirm.',
                                               'OTM structure: avoid paying up if move is already extended.'],
                                   'unfavorable': ['Avoid if price action weakens.',
                                                   'Avoid if momentum weakens.',
                                                   'Avoid if bid/ask widens materially.']},
             'decisionContext': {'today': {'rank': 2, 'candidateCount': 6, 'topPercent': 34, 'todayScore': 83},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': 9,
                                                'distinctTickerCount': 4,
                                                'winRate': 55.6,
                                                'avgReturnPct': 60.0,
                                                'avgRMultiple': None,
                                                'medianHoldDays': 8.0,
                                                'holdP25Days': 8.0,
                                                'holdP75Days': 8.0,
                                                'cohortLabel': 'Based on similar setups over the last 90 days',
                                                'matchStrength': 'setup',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Higher-priority setup with a clean enough entry profile.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   'RSI 50.9 stays below the late-extension zone.'],
                                 'invalidation': ['Skip if price moves more than 3% above the snapshot before entry.',
                                                  'Skip if RSI pushes into the 68-70 rejection zone before entry.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '8 trading days',
                                                 'baseCase': 'Orderly continuation if the trend and liquidity stay '
                                                             'intact.',
                                                 'risk': 'Premium can decay quickly if the move stalls.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}},
            {'rank': 3,
             'selector_rank': 3,
             'ticker': 'DELL',
             'signal_date': '2026-05-05',
             'companyName': 'Dell Technologies Inc.',
             'tier': 'A+',
             'final_tier': 'A+',
             'action': 'ENTER',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 99.312085,
             'global_percentile': 99.684012,
             'adaptive_score_final': 1.587692,
             'contract': {'optionSymbol': 'O:DELL260618C00210000',
                          'strike': 210,
                          'expiry': '2026-06-18',
                          'dte': 44,
                          'underlyingPrice': 216.32,
                          'distanceToStrikePct': -2.9,
                          'moneyness': '0.971',
                          'itmFlag': 'ATM',
                          'strikePositionLabel': 'ATM',
                          'strikePositionText': '2.9% below spot'},
             'market': {'volume': 155, 'openInterest': 3176},
             'context': {'sector': 'Technology', 'rsi': 64.4},
             'etfOverlay': {'etf': 'XLK', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.588,
                        'adjustedScoreFinal': 1.998,
                        'adaptiveScore': 1.388,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': None,
                        'recentWr': None,
                        'recentN': 0,
                        'degradation': None,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -6.657,
                        'evPct': -0.25,
                        'rankScore': 0.162,
                        'regimeAdj': 0.2,
                        'sectorScore': 0.674,
                        'rsiScore': 0.499},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'A',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': None,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 26.63,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': ["Higher-priority candidate in today's list."],
                                   'caution': ['No live sector overlay; use price action to confirm.'],
                                   'unfavorable': ['Avoid if price action weakens.',
                                                   'Avoid if momentum weakens.',
                                                   'Avoid if bid/ask widens materially.']},
             'decisionContext': {'today': {'rank': 3, 'candidateCount': 6, 'topPercent': 50, 'todayScore': 67},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': 25,
                                                'distinctTickerCount': 5,
                                                'winRate': 88.0,
                                                'avgReturnPct': 87.7,
                                                'avgRMultiple': None,
                                                'medianHoldDays': 9.0,
                                                'holdP25Days': 8.0,
                                                'holdP75Days': 9.0,
                                                'cohortLabel': 'Based on similar setups over the last 90 days',
                                                'matchStrength': 'setup',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Higher-priority setup with a clean enough entry profile.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   "Sector ranks #1 in today's conviction map."],
                                 'invalidation': ['Skip if price moves more than 3% above the snapshot before entry.',
                                                  'Skip if RSI pushes into the 68-70 rejection zone before entry.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '8-9 trading days',
                                                 'baseCase': 'Orderly continuation if the trend and liquidity stay '
                                                             'intact.',
                                                 'risk': 'The edge weakens if momentum cools and sector support '
                                                         'fades.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}},
            {'rank': 4,
             'selector_rank': 4,
             'ticker': 'QCOM',
             'signal_date': '2026-05-05',
             'companyName': 'QUALCOMM Incorporated',
             'tier': 'A',
             'final_tier': 'A',
             'action': 'WAIT',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 96.949486,
             'global_percentile': 97.8182,
             'adaptive_score_final': 1.121688,
             'contract': {'optionSymbol': 'O:QCOM260529C00200000',
                          'strike': 200,
                          'expiry': '2026-05-29',
                          'dte': 24,
                          'underlyingPrice': 186.55,
                          'distanceToStrikePct': 7.2,
                          'moneyness': '1.072',
                          'itmFlag': 'OTM',
                          'strikePositionLabel': 'OTM',
                          'strikePositionText': '7.2% above spot'},
             'market': {'volume': 1199, 'openInterest': 1485},
             'context': {'sector': 'Technology', 'rsi': 87.4},
             'etfOverlay': {'etf': 'XLK', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.122,
                        'adjustedScoreFinal': 1.532,
                        'adaptiveScore': 0.922,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': None,
                        'recentWr': None,
                        'recentN': 0,
                        'degradation': None,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -1.718,
                        'evPct': -0.25,
                        'rankScore': 0.218,
                        'regimeAdj': 0.2,
                        'sectorScore': 0.674,
                        'rsiScore': 1.224},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'A',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': False,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 6.87,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': [],
                                   'caution': ['No live sector overlay; use price action to confirm.',
                                               'OTM structure: avoid paying up if move is already extended.',
                                               'Momentum extended; avoid chasing strength.'],
                                   'unfavorable': ['Behind stronger names today; only revisit if conditions improve.']},
             'decisionContext': {'today': {'rank': 4, 'candidateCount': 6, 'topPercent': 67, 'todayScore': 50},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': 9,
                                                'distinctTickerCount': 4,
                                                'winRate': 55.6,
                                                'avgReturnPct': 60.0,
                                                'avgRMultiple': None,
                                                'medianHoldDays': 8.0,
                                                'holdP25Days': 8.0,
                                                'holdP75Days': 8.0,
                                                'cohortLabel': 'Based on similar setups over the last 90 days',
                                                'matchStrength': 'setup',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Broadly qualified, but not a priority versus cleaner names today.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   "Sector ranks #1 in today's conviction map."],
                                 'invalidation': ['Skip if price moves more than 2% above the snapshot before entry.',
                                                  'Skip if momentum extends further without a reset.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '8 trading days',
                                                 'baseCase': 'Secondary setup unless the tape improves.',
                                                 'risk': 'Premium can decay quickly if the move stalls.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}},
            {'rank': 5,
             'selector_rank': 5,
             'ticker': 'MRVL',
             'signal_date': '2026-05-05',
             'companyName': 'Marvell Technology, Inc.',
             'tier': 'A',
             'final_tier': 'A',
             'action': 'ENTER',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 96.27615,
             'global_percentile': 97.390214,
             'adaptive_score_final': 1.061022,
             'contract': {'optionSymbol': 'O:MRVL260529C00180000',
                          'strike': 180,
                          'expiry': '2026-05-29',
                          'dte': 24,
                          'underlyingPrice': 168.75,
                          'distanceToStrikePct': 6.7,
                          'moneyness': '1.067',
                          'itmFlag': 'OTM',
                          'strikePositionLabel': 'OTM',
                          'strikePositionText': '6.7% above spot'},
             'market': {'volume': 169, 'openInterest': 1833},
             'context': {'sector': 'Technology', 'rsi': 76.9},
             'etfOverlay': {'etf': 'XLK', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.061,
                        'adjustedScoreFinal': 1.061,
                        'adaptiveScore': 0.861,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': 0.4702,
                        'recentWr': 0.76,
                        'recentN': 25,
                        'degradation': 0.2898,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -3.053,
                        'evPct': -0.25,
                        'rankScore': 0.217,
                        'regimeAdj': 0.2,
                        'sectorScore': 0.674,
                        'rsiScore': 1.224},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'A',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': False,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 12.21,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': ["Higher-priority candidate in today's list."],
                                   'caution': ['No live sector overlay; use price action to confirm.',
                                               'OTM structure: avoid paying up if move is already extended.',
                                               'Momentum extended; avoid chasing strength.'],
                                   'unfavorable': ['Avoid if price action weakens.',
                                                   'Avoid if momentum rolls over after extension.',
                                                   'Avoid if bid/ask widens materially.']},
             'decisionContext': {'today': {'rank': 5, 'candidateCount': 6, 'topPercent': 84, 'todayScore': 33},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': 9,
                                                'distinctTickerCount': 4,
                                                'winRate': 55.6,
                                                'avgReturnPct': 60.0,
                                                'avgRMultiple': None,
                                                'medianHoldDays': 8.0,
                                                'holdP25Days': 8.0,
                                                'holdP75Days': 8.0,
                                                'cohortLabel': 'Based on similar setups over the last 90 days',
                                                'matchStrength': 'setup',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Strong continuation setup, but timing matters because momentum is '
                                                'already extended.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   "Sector ranks #1 in today's conviction map."],
                                 'invalidation': ['Skip if price moves more than 2% above the snapshot before entry.',
                                                  'Skip if momentum extends further without a reset.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '8 trading days',
                                                 'baseCase': 'Orderly continuation if the trend and liquidity stay '
                                                             'intact.',
                                                 'risk': 'Premium can decay quickly if the move stalls.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}},
            {'rank': 6,
             'selector_rank': 6,
             'ticker': 'NEM',
             'signal_date': '2026-05-05',
             'companyName': 'Newmont Corporation',
             'tier': 'A',
             'final_tier': 'A',
             'action': 'ENTER',
             'action_override': False,
             'optionType': 'call',
             'signalStrength': 'MODERATE',
             'segmented_percentile': 96.273416,
             'global_percentile': 97.389389,
             'adaptive_score_final': 1.060876,
             'contract': {'optionSymbol': 'O:NEM260618C00115000',
                          'strike': 115,
                          'expiry': '2026-06-18',
                          'dte': 44,
                          'underlyingPrice': 109.01,
                          'distanceToStrikePct': 5.5,
                          'moneyness': '1.055',
                          'itmFlag': 'OTM',
                          'strikePositionLabel': 'OTM',
                          'strikePositionText': '5.5% above spot'},
             'market': {'volume': 128, 'openInterest': 2997},
             'context': {'sector': 'Basic Materials', 'rsi': 48.1},
             'etfOverlay': {'etf': 'XLB', 'bias': 'No overlay', 'winRate4d': None, 'breadth': None},
             'scores': {'adaptiveScoreFinal': 1.061,
                        'adjustedScoreFinal': 0.445,
                        'adaptiveScore': 1.061,
                        'adaptiveRank': 0,
                        'scoreDecile': 10,
                        'baselineWr': None,
                        'recentWr': None,
                        'recentN': 0,
                        'degradation': None,
                        'regimeMultiplier': 1.0,
                        'priorityScore': 0.138,
                        'probCalibrated': 0.138,
                        'expectedValue': -1.32,
                        'evPct': -0.25,
                        'rankScore': 0.162,
                        'regimeAdj': 0.0,
                        'sectorScore': -0.242,
                        'rsiScore': -0.757},
             'classification': {'predictedTierCal': 'A',
                                'predictedTierRaw': 'A',
                                'adaptiveTier': 'C',
                                'filteredTier': 'A',
                                'regimeState': 'healthy',
                                'dteBucket': '22-45',
                                'vixBucket': '15-20'},
             'execution': {'liveEligible': True,
                           'selected': False,
                           'aPlus': False,
                           'rankAlpha': None,
                           'failReason': 'OK_BASE'},
             'risk': {'midPrice': 5.28,
                      'bidAskPct': None,
                      'bidOk': True,
                      'volumeOk': True,
                      'dteOk': True,
                      'spyTrendOk': True,
                      'liquidityOk': True,
                      'openInterestOk': True},
             'executionGuidance': {'favorable': ["Higher-priority candidate in today's list."],
                                   'caution': ['No live sector overlay; use price action to confirm.',
                                               'OTM structure: avoid paying up if move is already extended.'],
                                   'unfavorable': ['Avoid if price action weakens.',
                                                   'Avoid if momentum weakens.',
                                                   'Avoid if bid/ask widens materially.']},
             'decisionContext': {'today': {'rank': 6, 'candidateCount': 6, 'topPercent': 100, 'todayScore': 17},
                                 'historical': {'windowDays': 90,
                                                'sampleSize': None,
                                                'distinctTickerCount': None,
                                                'winRate': None,
                                                'avgReturnPct': None,
                                                'avgRMultiple': None,
                                                'medianHoldDays': None,
                                                'holdP25Days': None,
                                                'holdP75Days': None,
                                                'cohortLabel': None,
                                                'matchStrength': 'none',
                                                'supportLabel': 'Limited history'},
                                 'translation': 'Higher-priority setup with a clean enough entry profile.',
                                 'executionEdge': ['Spread and liquidity snapshot support cleaner fills.',
                                                   'No live sector overlay, so price action matters more than '
                                                   'backdrop.',
                                                   'RSI 48.1 stays below the late-extension zone.'],
                                 'invalidation': ['Skip if price moves more than 3% above the snapshot before entry.',
                                                  'Skip if RSI pushes into the 68-70 rejection zone before entry.',
                                                  'Skip if spread or liquidity deteriorates on the live chain.'],
                                 'expectation': {'timeframe': '1-2 weeks',
                                                 'baseCase': 'Orderly continuation if the trend and liquidity stay '
                                                             'intact.',
                                                 'risk': 'Premium can decay quickly if the move stalls.'}},
             'provenance': {'sourceFile': 'sample_predictions_with_tiers_20260505.csv',
                            'selectorFile': 'top_trades_latest.csv',
                            'strategyStatsFile': 'trades_master.duckdb',
                            'mlModelVersion': 'lgbm_bigwin25_calls_v1.joblib',
                            'filterVersion': 'filters_20251210.json',
                            'dataCutoff': '2025-12-10',
                            'runTimestamp': '2026-05-06 07:17:20',
                            'signalDate': '2026-05-05'}}]}
